### ISSUE TITLE
(SproutBillings) (MV) Sprout Invoices Add-on - Authorize.net Payments

### ISSUE THREAD

**Issue by tonyr-wv** [SproutApps/sprout-invoices#5] opened 2020-03-16 14:35 UTC
Users who have selected to use authorize.net as the payment processor for their invoices are receiving error code 3742 when their customer attempts to pay the invoice

Authorize.net has recently updated their API https://developer.authorize.net/api/system_changes.html

**Comment by bwmarkle** [comment] 2020-03-18 12:41
@tonyr-wv What is the full and exact error?

I googled `authorize.net 3742 error` but it didn't bring back much.

**Comment by tonyr-wv** [comment] 2020-03-19 12:36
I have had similar luck googling it, the exact code is Payment Error 3742
![payment-error-3742](https://user-images.githubusercontent.com/60514213/77068057-df1b0400-69dd-11ea-8707-09cdd828edde.jpg)

We reached out to Dan Cameron and he advised us the following:
Dan Cameron  6:24 PM It does look like Authorize.net stopped supporting an older SDK for CIM, which is a bit odd...

Dan Cameron  6:27 PM
... I was hoping a quick SDK update would work but it's much bigger than that, the whole class would need to be re-worked.

**Comment by bwmarkle** [comment] 2020-03-26 10:48
> I was hoping a quick SDK update would work but it's much bigger than that, the whole class would need to be re-worked.

@tonyr-wv that doesn't sound good. What are you thinking?

**Comment by tonyr-wv** [comment] 2020-03-26 12:14
I'm having support try another workaround, however we are running into errors when attempting to get the file. https://jira.imhdev.com/browse/T3O-2558 I'll update you with our findings

**Comment by elanasparkle** [comment] 2020-10-14 15:33
Authorize.net not working With Stripe billings PAYMENT ERROR: 3742

=========================================================
Name           |   response is empty and nothing is passed to authorize.net
Reporter       |   Elana D.
Submit Date |    10/14/2020
Summary      | using authorize.net CIM is the problem when you have sprout billings plugin activated
Reproduction steps | set up authorize.net with Sprout Invoices - Billings set up and process a payment you will receive PAYMENT ERROR: 3742 and no response is logged. 
Platform       | n/a
PHP Version | n/a
Browser        | n/a

Workaround: 
Disable the Sprout Invoices Billings plugin and set up authorize.net non-CIM integration.

**Comment by dancameron** [comment] 2021-01-25 19:16
FYI: "Payment Error: 3742" is a made up error, sprout-invoices-auto-billing/payment-processors/authorize-net-cim/SA_AuthorizeNet_CIM.php#228

The error is because no payment profile was found. I would guess the user's have issues with their CIM, so I'd ask them to see if their account is setup with CIM before going much further.

**Comment by elanasparkle** [comment] 2022-01-29 14:23
Moving to pro Sprout Invoices repository.

**Closed as completed by elanasparkle** 2022-01-29 14:23 UTC
Labels: bug
